title: 'hambern.portfolio::lang.item.label'
modelClass: Hambern\Portfolio\Models\Item
list: $/hambern/portfolio/models/item/columns.yaml
recordUrl: 'hambern/portfolio/items/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
